2024-11-16 10:15:14,304 - Starting file sync daemon monitoring: files
2024-11-16 10:15:14,304 - Remote sync target: 10.100.242.151:1234 files
2024-11-16 10:15:31,306 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/x.txt
2024-11-16 10:15:31,971 - Sync completed successfully
2024-11-16 10:15:42,514 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf
2024-11-16 10:15:42,753 - Sync completed successfully
2024-11-16 10:15:54,304 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/x.txt~, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf
2024-11-16 10:15:54,525 - Sync completed successfully
2024-11-16 10:16:03,008 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf
2024-11-16 10:16:03,229 - Sync completed successfully
2024-11-16 10:16:17,072 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-16 10:16:17,291 - Sync completed successfully
2024-11-16 10:21:52,989 - Stopping file sync daemon
2024-11-16 22:15:32,928 - Starting file sync daemon monitoring: files/
2024-11-16 22:15:32,928 - Remote sync target: 192.168.143.49:1234 files/
2024-11-16 22:15:58,671 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/makima.txt
2024-11-16 22:16:57,768 - Sync failed with exit code: 2
2024-11-16 22:16:57,769 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/makima.txt
2024-11-16 22:17:01,168 - Sync failed with exit code: 2
2024-11-16 22:17:01,168 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/10gb_file, /Users/ghost/Ventus/daemon/files/makima.txt
2024-11-16 22:17:06,209 - Sync failed with exit code: 2
2024-11-16 22:17:06,210 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/10gb_file, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/makima.txt
2024-11-16 22:17:06,472 - Sync failed with exit code: 2
2024-11-16 22:17:06,679 - Stopping file sync daemon
2024-11-16 22:18:01,261 - Starting file sync daemon monitoring: files/
2024-11-16 22:18:01,261 - Remote sync target: 192.168.143.49:1234 files/
2024-11-16 22:18:18,368 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/4913
2024-11-16 22:19:36,658 - Sync completed successfully
2024-11-16 22:20:24,903 - Stopping file sync daemon
2024-11-16 22:20:34,613 - Starting file sync daemon monitoring: files/
2024-11-16 22:20:34,614 - Remote sync target: 192.168.143.49:1234 files/
2024-11-16 22:21:01,884 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/4913
2024-11-16 22:25:02,437 - Sync completed successfully
2024-11-17 02:32:06,419 - Stopping file sync daemon
2024-11-22 23:40:19,158 - Starting file sync daemon monitoring: files/
2024-11-22 23:40:19,158 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:41:36,036 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:44:16,954 - Sync failed with exit code: 2
2024-11-22 23:44:16,956 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:44:17,672 - Sync failed with exit code: 2
2024-11-22 23:44:18,618 - Stopping file sync daemon
2024-11-22 23:44:19,913 - Starting file sync daemon monitoring: files/
2024-11-22 23:44:19,914 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:45:00,475 - Stopping file sync daemon
2024-11-22 23:45:01,471 - Starting file sync daemon monitoring: files/
2024-11-22 23:45:01,471 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:45:13,529 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/lol.txt
2024-11-22 23:45:21,038 - Sync completed successfully
2024-11-22 23:46:37,429 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/xf.txt, /Users/ghost/Ventus/daemon/files/lol.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-22 23:46:54,992 - Sync failed with exit code: 2
2024-11-22 23:46:54,993 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/xf.txt, /Users/ghost/Ventus/daemon/files/lol.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-22 23:46:55,816 - Sync failed with exit code: 2
2024-11-22 23:46:55,816 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/xf.txt, /Users/ghost/Ventus/daemon/files/lol.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-22 23:46:56,027 - Sync failed with exit code: 2
2024-11-22 23:46:56,027 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/xf.txt, /Users/ghost/Ventus/daemon/files/lol.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-22 23:46:56,216 - Sync failed with exit code: 2
2024-11-22 23:46:56,421 - Stopping file sync daemon
2024-11-22 23:46:57,397 - Starting file sync daemon monitoring: files/
2024-11-22 23:46:57,397 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:47:26,828 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/lol.txt
2024-11-22 23:52:11,618 - Sync failed with exit code: 2
2024-11-22 23:52:12,327 - Stopping file sync daemon
2024-11-22 23:52:24,608 - Starting file sync daemon monitoring: files/
2024-11-22 23:52:24,608 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:52:33,256 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/m.txt
2024-11-22 23:52:47,427 - Sync failed with exit code: 2
2024-11-22 23:52:47,736 - Stopping file sync daemon
2024-11-22 23:53:36,533 - Starting file sync daemon monitoring: files/
2024-11-22 23:53:36,533 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:53:47,806 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/makima.txt
2024-11-22 23:55:00,207 - Sync completed successfully
2024-11-22 23:55:06,267 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/video.mp4, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/alsoTest/crazy.txt, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/test/hello.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:21,169 - Sync completed successfully
2024-11-22 23:56:41,662 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:55,815 - Sync failed with exit code: 2
2024-11-22 23:56:55,816 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:56,532 - Sync failed with exit code: 2
2024-11-22 23:56:56,532 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:56,778 - Sync failed with exit code: 2
2024-11-22 23:56:56,778 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:56,978 - Sync failed with exit code: 2
2024-11-22 23:56:56,978 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:57,162 - Sync failed with exit code: 2
2024-11-22 23:56:57,162 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:57,351 - Sync failed with exit code: 2
2024-11-22 23:56:57,352 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:57,620 - Sync failed with exit code: 2
2024-11-22 23:56:57,620 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:57,863 - Sync failed with exit code: 2
2024-11-22 23:56:57,863 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:58,447 - Sync failed with exit code: 2
2024-11-22 23:56:58,447 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:58,948 - Sync failed with exit code: 2
2024-11-22 23:56:58,948 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,032 - Sync failed with exit code: 2
2024-11-22 23:56:59,032 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,116 - Sync failed with exit code: 2
2024-11-22 23:56:59,116 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,200 - Sync failed with exit code: 2
2024-11-22 23:56:59,200 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,283 - Sync failed with exit code: 2
2024-11-22 23:56:59,283 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,367 - Sync failed with exit code: 2
2024-11-22 23:56:59,367 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,450 - Sync failed with exit code: 2
2024-11-22 23:56:59,450 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,534 - Sync failed with exit code: 2
2024-11-22 23:56:59,534 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,617 - Sync failed with exit code: 2
2024-11-22 23:56:59,617 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,700 - Sync failed with exit code: 2
2024-11-22 23:56:59,700 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,783 - Sync failed with exit code: 2
2024-11-22 23:56:59,783 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,866 - Sync failed with exit code: 2
2024-11-22 23:56:59,866 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:56:59,950 - Sync failed with exit code: 2
2024-11-22 23:56:59,950 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/sample.pdf, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/hello.txt, /Users/ghost/Ventus/daemon/files/womp_womp/hmm.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/ftest/test.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/4913, /Users/ghost/Ventus/daemon/files/file.py~, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/xf.txt
2024-11-22 23:57:00,033 - Sync failed with exit code: 2
2024-11-22 23:57:00,117 - Stopping file sync daemon
2024-11-22 23:57:46,240 - Starting file sync daemon monitoring: files/
2024-11-22 23:57:46,240 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:57:54,681 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/x.txt
2024-11-22 23:58:22,369 - Sync failed with exit code: 2
2024-11-22 23:58:22,934 - Stopping file sync daemon
2024-11-22 23:58:23,859 - Starting file sync daemon monitoring: files/
2024-11-22 23:58:23,859 - Remote sync target: 192.168.229.20:1234 files/
2024-11-22 23:58:34,173 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/x.txt
2024-11-23 00:07:34,848 - Sync failed with exit code: 2
2024-11-23 00:07:34,851 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf
2024-11-23 00:07:36,615 - Sync failed with exit code: 2
2024-11-23 00:07:36,615 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf
2024-11-23 00:07:38,314 - Sync failed with exit code: 2
2024-11-23 00:07:38,315 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf
2024-11-23 00:07:38,697 - Sync failed with exit code: 2
2024-11-23 00:07:38,697 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-23 00:07:38,914 - Sync failed with exit code: 2
2024-11-23 00:07:38,914 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-23 00:07:39,152 - Sync failed with exit code: 2
2024-11-23 00:07:39,152 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt
2024-11-23 00:07:39,357 - Sync failed with exit code: 2
2024-11-23 00:07:39,357 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/hp.epub
2024-11-23 00:07:39,553 - Sync failed with exit code: 2
2024-11-23 00:07:39,553 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/hp.epub
2024-11-23 00:07:39,740 - Sync failed with exit code: 2
2024-11-23 00:07:39,741 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/video2.mp4
2024-11-23 00:07:39,936 - Sync failed with exit code: 2
2024-11-23 00:07:39,936 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/video2.mp4
2024-11-23 00:07:40,121 - Sync failed with exit code: 2
2024-11-23 00:07:40,122 - Running sync for changes in: /Users/ghost/Ventus/daemon/files/test.py, /Users/ghost/Ventus/daemon/files/random_file.bin, /Users/ghost/Ventus/daemon/files/makima.txt, /Users/ghost/Ventus/daemon/files/x.txt, /Users/ghost/Ventus/daemon/files/sample2.pdf, /Users/ghost/Ventus/daemon/files/file.py, /Users/ghost/Ventus/daemon/files/tello.txt, /Users/ghost/Ventus/daemon/files/m.txt, /Users/ghost/Ventus/daemon/files/hp.epub, /Users/ghost/Ventus/daemon/files/video2.mp4
2024-11-23 00:07:40,305 - Sync failed with exit code: 2
2024-11-23 00:07:40,466 - Stopping file sync daemon
